// Expense category keyword dictionary and merchant‑to‑category map
//
// This file contains two exported constants:
// 1. CATEGORY_KEYWORDS – a mapping of expense categories to arrays of
//    lower‑cased keywords.  Keywords include descriptive terms that users
//    commonly use when logging expenses, names of major U.S. merchants,
//    regional chains and abbreviations, common misspellings and shorthand,
//    and verbs indicating the action taken.  Each category has at least
//    forty entries to maximize recall.
// 2. MERCHANT_CATEGORIES – a mapping from merchant names (as they appear on
//    receipts or statements) to a single category.  There are at least
//    eighty merchants covered across all categories.  Each merchant is
//    assigned to the most likely category and does not appear in multiple
//    categories.

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'Food & Drink': [
    // Common meal descriptions
    'lunch', 'dinner', 'breakfast', 'brunch', 'snacks', 'coffee', 'tea', 'drinks', 'bar', 'pub',
    'restaurant', 'dine out', 'takeout', 'take‑out', 'take away', 'fast food', 'meal',
    'happy hour', 'eat', 'dine', 'brewery', 'taproom', 'bakery', 'cafe', 'deli', 'food truck',
    'buffet', 'supper', 'grill', 'bistro', 'wine', 'cocktail', 'beer', 'beverage', 'canteen',
    // Major national and regional chains (plus common shorthand/misspellings)
    "mcdonald's", 'mcds', 'mcdo', 'macs', 'starbucks', 'stbx', 'dunkin', "dunkin' donuts",
    'dunkin donuts', 'chipotle', 'chipolte', 'taco bell', 'tbell', 'chick‑fil‑a',
    'chick fil a', 'cfa', "wendy's", 'wendys', 'subway', 'pizza hut', 'pizzahut', "domino's",
    'dominos', 'burger king', 'bk', 'panera', 'panera bread', 'kfc', 'popeyes',
    'jack in the box', 'jackinthebox', "arby's", 'arbys', 'sonic', 'qdoba', "chili's",
    'chilis', "applebee's", 'applebees', 'red lobster', 'olive garden', 'cheesecake factory',
    'outback', 'longhorn steakhouse', 'texas roadhouse', 'buffalo wild wings', 'bww',
    "raising cane's", 'canes', "jersey mike's", 'jersey mikes', 'shake shack', 'shakeshack',
    'in‑n‑out', 'in n out', 'innout', 'in and out', 'whataburger', "culver's", 'culvers',
    'wawa', 'sheetz', 'jimmy johns', "jimmy john's", 'five guys', 'panda express', 'del taco',
    'white castle',
    // Ordering and delivery verbs
    'ordered', 'grabbed', 'picked up', 'dined at', 'ate at', 'had a meal', 'got food',
    'to‑go order', 'delivery', 'grubhub', 'uber eats', 'doordash', 'seamless', 'postmates'
  ],

  'Groceries': [
    // Descriptive terms for grocery shopping
    'groceries', 'grocery', 'supermarket', 'super market', 'market', 'grocery run',
    'food shopping', 'produce', 'fruit', 'vegetables', 'veggies', 'meat', 'dairy',
    'bread', 'milk', 'eggs', 'pantry', 'bulk', 'staples', 'supplies', 'bottled water',
    'snacks', 'cereal', 'frozen food', 'canned goods', 'stocked up', 'restock',
    'grocery pickup', 'curbside', 'instacart', 'shipt', 'coupons', 'farmers market',
    'co‑op', 'organic', 'delivery',
    // Major grocery retailers (no duplicates across categories)
    'walmart', 'wal‑mart', 'costco', 'cosco', 'kroger', "kroger's", 'albertsons',
    'safeway', 'publix', 'whole foods', 'wholefoods', "trader joe's", 'trader joe', "tj's",
    'aldi', 'heb', 'h‑e‑b', 'meijer', 'wegmans', 'winco', 'weiss', "smith's", 'smiths',
    'harris teeter', 'king soopers', 'stop & shop', 'stop and shop', 'giant', 'giant eagle',
    'sprouts', 'food lion', 'foodlion', "shaw's", 'shaws', 'qfc', 'fred meyer', 'fredmeyer',
    'ralphs', 'vons', 'piggly wiggly', 'pigglywiggly', 'hy‑vee', 'hyvee', 'save mart',
    'savemart', 'winn‑dixie', 'winndixie', 'wegman’s', 'wegmens', 'cost co',
    // Convenience stores that function as grocery stops
    '7‑eleven', '7 eleven', 'seven eleven', 'circle k', "casey's", 'buc‑ee’s', 'bucees',
    'quiktrip', 'quicktrip', 'kwik trip', 'family dollar', 'dollar tree', 'dollar general',
    'bj’s wholesale', "bj's", 'grocery outlet',
    // Action words
    'grocery shopping', 'picked up groceries', 'bought groceries'
  ],

  'Transport': [
    // General transport terms
    'bus', 'train', 'subway', 'metro', 'taxi', 'cab', 'rideshare', 'ride share', 'carpool',
    'commute', 'fare', 'toll', 'parking', 'parking meter', 'parking ticket', 'gas', 'petrol',
    'fuel', 'travel card', 'ez pass', 'e‑zpass', 'e‑z pass', 'metrocard', 'clipper', 'orca',
    'ventra', 'farecard',
    // Ride‑hailing services
    'uber', 'uberx', 'uber xl', 'lyft', 'lyft ride', 'via', 'turo',
    // Public transit brands
    'amtrak', 'greyhound', 'megabus', 'septa', 'mta', 'bart', 'caltrain', 'metrolink',
    'metro north', 'sound transit',
    // Gas and convenience station brands (assigned here because of fuel purchases)
    'shell', 'exxon', 'exxon mobil', 'marathon', 'chevron', 'valero', 'citgo', 'phillips 66',
    'phillips66', 'conoco', 'bp', 'sunoco', "love's", 'loves', 'pilot', 'flying j',
    'pilot flying j', 'speedway', 'racetrac', 'race trac', 'casey’s', "casey's", 'maverik',
    'quiktrip', 'quicktrip', 'sheetz', 'kum & go', 'kum and go', 'thorntons', 'buc‑ee’s',
    'bucees',
    // Action phrases
    'filled up', 'topped up gas', 'refueled', 'transit fare', 'bus pass', 'subway ride',
    'parking garage'
  ],

  'Accommodation': [
    // Descriptive lodging terms
    'hotel', 'motel', 'inn', 'bed and breakfast', 'b&b', 'bnb', 'airbnb', 'vrbo',
    'vacation rental', 'hostel', 'resort', 'lodge', 'guesthouse', 'suite', 'room',
    'overnight stay', 'accommodation', 'lodging', 'stay', 'cabin', 'campground',
    'camping', 'camp site',
    // Hotel brands and booking platforms
    'hilton', 'hampton inn', 'doubletree', 'embassy suites', 'hilton garden inn', 'marriott',
    'courtyard', 'residence inn', 'ritz‑carlton', 'sheraton', 'westin', 'w hotels',
    'delta hotels', 'four points', 'renaissance hotel', 'fairfield inn', 'springhill suites',
    'choice hotels', 'comfort inn', 'comfort suites', 'quality inn', 'sleep inn',
    'econo lodge', 'clarion', 'ascend hotel collection', 'wyndham', 'days inn', 'super 8',
    'ramada', 'la quinta', 'microtel', 'baymont', 'ihg', 'holiday inn', 'holiday inn express',
    'candlewood suites', 'crowne plaza', 'intercontinental', 'staybridge suites',
    'best western', 'hyatt', 'hyatt place', 'hyatt house', 'grand hyatt', 'park hyatt',
    'andaz', 'sonesta', 'red roof inn', 'four seasons', 'drury inn', 'aloft', 'kimpton',
    // Booking and travel sites
    'booking.com', 'expedia', 'hotels.com', 'kayak', 'priceline', 'orbitz', 'travelocity',
    // Spelling variants and abbreviations
    'accomodation', 'accomodations', 'mariott', 'mariot', 'sheriton',
    // Actions
    'booked hotel', 'reserved room', 'hotel reservation', 'staying at'
  ],

  'Entertainment': [
    // General entertainment and event terms
    'movie', 'movies', 'cinema', 'theatre', 'theater', 'concert', 'show', 'play', 'musical',
    'opera', 'festival', 'amusement park', 'theme park', 'club', 'game', 'sports event',
    'bowling', 'mini golf', 'minigolf', 'skating', 'arcade', 'karaoke', 'escape room',
    'board games',
    // Streaming and music services
    'netflix', 'netflex', 'prime video', 'amazon prime video', 'hulu', 'disney plus',
    'disney+', 'disny plus', 'max', 'hbo max', 'hbo', 'apple tv', 'apple tv+',
    'paramount plus', 'paramount+', 'peacock', 'peacock tv', 'starz', 'showtime',
    'youtube premium', 'youtube tv', 'spotify', 'pandora', 'apple music', 'tidal', 'siriusxm',
    'audible', 'soundcloud',
    // Ticketing and cinemas
    'amc theatres', 'amc', 'regal', 'regal cinemas', 'cinemark', 'fandango', 'ticketmaster',
    'live nation', 'stubhub', 'axs', 'eventbrite', 'bandsintown',
    // Gaming services
    'xbox game pass', 'gamepass', 'playstation plus', 'ps plus', 'psn', 'nintendo switch online',
    'switch online', 'steam', 'epic games', 'twitch',
    // Sports streaming services
    'espn+', 'nba league pass', 'mlb tv', 'nfl+', 'nhl tv',
    // Action and descriptive words
    'streaming', 'subscription', 'watched', 'movie night', 'concert tickets', 'binge',
    'rented movie'
  ],

  'Utilities': [
    // Generic utility descriptors
    'electricity', 'electric bill', 'power bill', 'gas bill', 'natural gas', 'water bill',
    'utility', 'utilities', 'internet', 'wifi', 'broadband', 'phone bill', 'mobile plan',
    'cell phone', 'cable', 'tv bill', 'trash', 'sewer', 'heating', 'cooling', 'propane',
    // Major internet, phone and cable providers
    'xfinity', 'comcast', 'x finity', 'at&t', 'att', 'verizon', 'verizon fios', 't‑mobile',
    'tmobile', 'spectrum', 'charter', 'cox', 'centurylink', 'frontier', 'windstream',
    'google fiber', 'starlink', 'hughesnet', 'dish', 'directv', 'dish network', 'metronet',
    'fios', 'wow!', 'rcn', 'mediacom', 'optimum', 'altice', 'consolidated communications',
    // Energy companies
    'pge', 'pg&e', 'pacific gas and electric', 'con edison', 'coned', 'duke energy',
    'dominion energy', 'southern california edison', 'sce', 'florida power & light', 'fpl',
    'georgia power', 'nyseg', 'national grid', 'xcel energy', 'sdg&e', 'sdge', 'og&e',
    // Action words and misspellings
    'utilites', 'utilitie', 'elec', 'hydro', 'bill pay', 'mobile', 'paid bill', 'utility payment',
    'autopay'
  ],

  'Healthcare': [
    // General healthcare descriptors
    'doctor', 'dentist', 'orthodontist', 'clinic', 'hospital', 'urgent care', 'emergency room',
    'er', 'checkup', 'physical', 'appointment', 'co‑pay', 'copay', 'medicine', 'medication',
    'prescription', 'rx', 'pharmacy', 'pharm', 'drug store', 'drugstore', 'lab test', 'xray',
    'mri', 'therapy', 'counseling', 'mental health', 'vaccination', 'vaccine', 'optometrist',
    'eye doctor', 'eyecare', 'eye exam', 'therapist', 'psychologist', 'psychiatrist',
    'chiropractor', 'massage therapy', 'veterinarian', 'vet', 'dental cleaning', 'physician',
    'dermatologist', 'specialist',
    // Pharmacy chains and healthcare providers
    'cvs pharmacy', 'cvs', 'walgreens', 'walgreens pharmacy', 'health mart',
    'good neighbor pharmacy', 'gnc', 'geno healthcare', 'safeway pharmacy',
    'the vitamin shoppe', 'vitamin shoppe', 'albertsons pharmacy', 'medicine shoppe', 'rite aid',
    'riteaid', 'publix pharmacy', 'kroger pharmacy', 'costco pharmacy', 'meijer pharmacy',
    // Hospital and healthcare systems
    'kaiser permanente', 'mayo clinic', 'cleveland clinic', 'hca healthcare', 'ascension',
    'tenet healthcare', 'sutter health', 'partners healthcare', 'new york‑presbyterian',
    'cedars‑sinai',
    // Insurance companies
    'blue cross', 'blue shield', 'bcbs', 'unitedhealth', 'uhc', 'aetna', 'humana', 'cigna',
    // Misspellings and shorthand
    'pharamcy', 'pharmcy', 'perscription', 'medicene', 'meds', 'vax', 'appt', 'doc',
    // Action phrases
    'doctor visit', 'filled prescription', 'refill', 'vaccination', 'clinic visit',
    'co pay'
  ],

  'Shopping': [
    // General retail terms
    'shopping', 'shop', 'purchase', 'bought', 'buy', 'bargain', 'mall', 'store', 'retail',
    'retail therapy', 'clothes shopping', 'shoe shopping', 'electronics', 'furniture',
    'home goods', 'homegoods', 'tech', 'online shopping', 'marketplace', 'package', 'delivery',
    'shopping spree', 'sale', 'clearance', 'discount',
    // Major retailers (assigned here rather than groceries)
    'amazon', 'amazon.com', 'amzn', 'target', 'tgt', 'best buy', 'bestbuy', 'bby',
    'home depot', 'home depot', 'hd', 'lowe’s', 'lowes', 'bed bath & beyond', 'bed bath and beyond',
    'homegoods', 'tj maxx', 'tjmaxx', 'marshalls', 'ross', 'ross dress for less', "macy's", 'macys',
    'nordstrom', 'kohls', 'jcpenney', 'jc penney', 'jcp', "dillard's", 'dillards', 'belk',
    'academy sports', 'academy sports + outdoors', "dick's sporting goods", 'dicks',
    'ikea', 'ikeea', 'five below', 'big lots', 'biglots', 'dollar tree', 'family dollar',
    'dollar general', 'sams club', "sam's club", "bj's wholesale", "bj's", 'costco online',
    'tjx', 'gamestop', 'gamestop.com', 'staples', 'office depot', 'office max', 'b&h photo',
    'micro center', 'microcenter', 'frys', 'cabela’s', 'bass pro', 'ultra',
    // Action words
    'purchased', 'ordered', 'delivered', 'shopped', 'gift', 'return', 'exchange'
  ],

  'Travel': [
    // General travel descriptors
    'flight', 'airfare', 'plane ticket', 'air ticket', 'airline ticket', 'train ticket',
    'travel', 'trip', 'journey', 'vacation', 'holiday', 'getaway', 'road trip',
    'travel booking', 'ticket', 'ride', 'ferry', 'cruise',
    // Airlines (big four and more)
    'american airlines', 'american', 'delta', 'delta airlines', 'southwest',
    'southwest airlines', 'united', 'united airlines', 'alaska airlines', 'alaska air',
    'jetblue', 'jet blue', 'spirit', 'spirit airlines', 'frontier', 'frontier airlines',
    'allegiant', 'allegiant airlines', 'hawaiian airlines', 'sun country',
    // Cruises
    'carnival cruise', 'royal caribbean', 'norwegian cruise', 'msc cruises',
    'princess cruise', 'disney cruise line',
    // Booking and travel agencies
    'expedia', 'priceline', 'kayak', 'orbitz', 'hotwire', 'travelocity', 'hopper',
    'trivago', 'cheapoair', 'cheap o air',
    // Car rental companies
    'enterprise', 'hertz', 'avis', 'budget', 'alamo', 'national car rental', 'national',
    'thrifty', 'dollar car rental', 'dollar', 'payless car rental', 'sixt', 'u‑haul', 'uhaul',
    'zipcar', 'turo',
    // Action phrases
    'booked flight', 'flight purchase', 'plane ride', 'roadtrip', 'vacation booked',
    'ticketed', 'checked baggage', 'boarding pass'
  ],

  'Education': [
    // General education descriptors
    'tuition', 'tuition fee', 'fees', 'school', 'college', 'university', 'course', 'courses',
    'class', 'classes', 'lessons', 'workshop', 'training', 'seminar', 'education', 'study',
    'studying', 'degree', 'certificate', 'exam', 'lab fee', 'textbook', 'books', 'e‑learning',
    'mooc', 'learning', 'student loan', 'loan payment', 'scholarship', 'registration',
    'application fee', 'testing fee',
    // Online learning platforms
    'coursera', 'coursra', 'udemy', 'udemey', 'linkedin learning', 'lynda', 'edx', 'edx.org',
    'skillshare', 'masterclass', 'khan academy', 'khanacad', 'udacity', 'futurelearn',
    'pluralsight', 'codecademy', 'brilliant', 'datacamp', 'duolingo', 'rosetta stone',
    // Universities and colleges
    'mit', 'massachusetts institute of technology', 'princeton', 'harvard', 'stanford', 'caltech',
    'california institute of technology', 'uc berkeley', 'berkeley', 'yale',
    'university of pennsylvania', 'upenn', 'penn', 'university of chicago', 'uchicago',
    'johns hopkins', 'cornell', 'ucla', 'columbia', 'university of michigan', 'michigan',
    'carnegie mellon', 'cmu', 'duke', 'northwestern', 'nyu', 'university of texas',
    'texas a&m', 'ohio state', 'florida state', 'university of florida', 'university of washington',
    // Education services
    'chegg', 'barnes & noble', 'bn', 'bookstore', 'kaplan', 'princeton review',
    // Exams and certifications
    'gre', 'gmat', 'sat', 'act', 'toefl', 'ielts', 'bar exam',
    // Misspellings and abbreviations
    'tution', 'unversity', 'cours', 'loans', 'uni', 'edu',
    // Action phrases
    'studied', 'enrolled', 'registered', 'took course', 'took exam', 'training session'
  ],

  'Fitness & Sports': [
    // General fitness and sports descriptors
    'gym', 'fitness', 'workout', 'exercise', 'training', 'training session', 'gym membership',
    'yoga', 'pilates', 'zumba', 'spin class', 'spinning', 'cycling', 'crossfit', 'aerobics',
    'hiit', 'weightlifting', 'weights', 'running', 'jogging', 'treadmill', 'swimming',
    'basketball', 'football', 'tennis', 'soccer', 'golf', 'gymnastics', 'dance class',
    'kickboxing', 'martial arts', 'boxing', 'marathon', 'race registration', 'triathlon',
    'sports league', 'personal trainer',
    // Gym and fitness chains
    'planet fitness', 'pf', 'anytime fitness', 'la fitness', 'crunch fitness', '24 hour fitness',
    '24hr fitness', 'snap fitness', 'orangetheory', 'orangetheory fitness', 'otf',
    'f45 training', 'f45', 'workout anytime', 'retro fitness', 'equinox', 'equinox fitness',
    'life time', 'lifetime fitness', 'club pilates', "barry's bootcamp", 'barrys bootcamp',
    'barrys', 'soulcycle', 'cyclebar', 'pure barre', 'row house', '9round', 'peloton',
    'gympass', 'classpass',
    // Sporting goods and apparel brands
    "nike", "adidas", "lululemon", "under armour", "under armor", "foot locker", "champs sports",
    'finish line', 'rogue fitness', 'big 5 sporting goods', 'academy sports', 'athleta',
    // Action phrases and misspellings
    'worked out', 'ran', 'gym session', 'fitness class', 'exercise class', 'training program',
    'fitnes', 'gymm'
  ],

  'Personal Care': [
    // General personal care terms
    'haircut', 'hair cut', 'hair', 'barber', 'hair salon', 'salon', 'barbershop', 'spa',
    'nails', 'manicure', 'pedicure', 'mani', 'pedi', 'massage', 'facial', 'waxing', 'wax',
    'eyebrows', 'brows', 'lashes', 'lash', 'beauty', 'cosmetics', 'makeup', 'skincare',
    'skin care', 'dermatology', 'tattoo', 'piercing', 'hair color', 'dyed hair', 'shave',
    'trim', 'grooming', 'beard trim', 'braids', 'hairdresser', 'blowout', 'beauty products',
    'personal care',
    // Salon and beauty chains
    'supercuts', 'smartstyle', 'jcpenney salon', 'jc penney salon', 'cost cutters',
    'salon lofts', 'amazing lash studio', 'signature style salons', 'holiday hair', 'deka lash',
    'hairmasters', 'great clips', 'sport clips', 'sportclips', 'ulta', 'ulta beauty', 'sephora',
    'mac cosmetics', 'clinique', 'estee lauder', 'bath & body works', 'body shop', 'lush', 'aveda',
    'sally beauty', 'beauty supply', 'cosmo prof', 'drybar', 'european wax center', 'massage envy',
    'hand and stone', 'pro nails', 'nail salon', 'nail bar', 'tanning salon',
    // Misspellings and shorthand
    'saloon', 'manacure', 'pedcure', 'massge', 'mani pedi', 'self‑care',
    // Action phrases
    'got hair done', 'got a haircut', 'nail appointment', 'spa day', 'massage session', 'waxed'
  ],

  'Fees & Charges': [
    // Generic fee and charge descriptors
    'fee', 'fees', 'charge', 'charges', 'service fee', 'bank fee', 'overdraft', 'nsf fee',
    'account fee', 'maintenance fee', 'late fee', 'interest charge', 'finance charge',
    'atm fee', 'foreign transaction', 'wire transfer', 'processing fee', 'subscription fee',
    'annual fee', 'penalty', 'parking fine', 'ticket', 'fine', 'toll fee', 'transaction fee',
    'withdrawal fee', 'returned check',
    // Banks and financial institutions
    'chase', 'jp morgan chase', 'bank of america', 'wells fargo', 'citibank', 'citi',
    'us bank', 'pnc bank', 'pnc', 'truist', 'capital one', 'td bank', 'bmo', 'first citizens bank',
    'citizens bank', 'fifth third bank', 'm&t bank', 'huntington bank', 'ally bank', 'keybank',
    'hsbc', 'regions bank', 'american express', 'amex', 'discover', 'visa', 'mastercard', 'paypal',
    'venmo', 'cash app', 'zelle', 'stripe', 'square', 'intuit', 'quickbooks', 'coinbase',
    'robinhood',
    // Government agencies and other fee issuers
    'irs', 'dmv', 'state tax', 'property tax', 'court fee', 'hoa', 'hoa fee', 'license fee',
    'passport fee', 'visa fee',
    // Misspellings and abbreviations
    'feee', 'charg', 'intrest', 'atm', 'ach', 'od fee',
    // Action phrases
    'interest', 'penalty fee', 'overdraft fee', 'service charge'
  ],

  'Other': [
    // Generic catch‑all terms
    'other', 'misc', 'miscellaneous', 'unknown', 'uncategorized', 'general', 'random', 'various',
    'stuff', 'etc', 'n/a', 'misc expense', 'sundry',
    // Non‑categorical expenditures
    'gift', 'gifts', 'donation', 'charity', 'church', 'offering', 'tithe', 'pet care', 'pet supplies',
    'vet bill', 'petco', 'petsmart', 'home improvement', 'cleaning supplies', 'laundry',
    'dry cleaning', 'home repair', 'contractor', 'maintenance', 'insurance premium', 'insurance',
    'taxes', 'tax payment', 'irs payment', 'dmv fee', 'license renewal', 'passport', 'visa',
    'fine', 'parking ticket', 'child care', 'daycare', 'babysitter',
    // Donation and crowdfunding platforms
    'goodwill', 'salvation army', 'red cross', 'united way', 'gofundme', 'go fund me',
    'patreon', 'kickstarter', 'indiegogo',
    // Misspellings and shorthand
    'miscellaneous expense', 'miscelaneous', 'donaton', 'charaty', 'unkown',
    // Action phrases
    'donated', 'gifted', 'gave', 'random purchase', 'misc purchase'
  ]
};

export const MERCHANT_CATEGORIES: Record<string, string> = {
  // Food & Drink merchants
  "mcdonald's": 'Food & Drink',
  'starbucks': 'Food & Drink',
  'dunkin': 'Food & Drink',
  'chick‑fil‑a': 'Food & Drink',
  'taco bell': 'Food & Drink',
  "wendy's": 'Food & Drink',
  'chipotle': 'Food & Drink',
  'subway': 'Food & Drink',
  'pizza hut': 'Food & Drink',
  "domino's": 'Food & Drink',
  'burger king': 'Food & Drink',
  'panera': 'Food & Drink',
  'kfc': 'Food & Drink',
  'popeyes': 'Food & Drink',
  'jack in the box': 'Food & Drink',
  "arby's": 'Food & Drink',
  'sonic': 'Food & Drink',
  'qdoba': 'Food & Drink',
  "chili's": 'Food & Drink',
  "applebee's": 'Food & Drink',
  'red lobster': 'Food & Drink',
  'olive garden': 'Food & Drink',
  'cheesecake factory': 'Food & Drink',
  'outback': 'Food & Drink',
  'texas roadhouse': 'Food & Drink',
  "raising cane's": 'Food & Drink',
  "jersey mike's": 'Food & Drink',
  'shake shack': 'Food & Drink',
  'in‑n‑out': 'Food & Drink',
  'whataburger': 'Food & Drink',
  "culver's": 'Food & Drink',
  'wawa': 'Food & Drink',
  'sheetz': 'Food & Drink',
  "jimmy john's": 'Food & Drink',
  'five guys': 'Food & Drink',
  'panda express': 'Food & Drink',
  'del taco': 'Food & Drink',
  'white castle': 'Food & Drink',

  // Groceries merchants
  'walmart': 'Groceries',
  'costco': 'Groceries',
  'kroger': 'Groceries',
  'albertsons': 'Groceries',
  'safeway': 'Groceries',
  'publix': 'Groceries',
  'whole foods': 'Groceries',
  "trader joe's": 'Groceries',
  'aldi': 'Groceries',
  'heb': 'Groceries',
  'meijer': 'Groceries',
  'wegmans': 'Groceries',
  'winco': 'Groceries',
  'harris teeter': 'Groceries',
  'food lion': 'Groceries',
  'giant': 'Groceries',
  'sprouts': 'Groceries',
  '7‑eleven': 'Groceries',
  'circle k': 'Groceries',
  "bj's wholesale": 'Groceries',
  'grocery outlet': 'Groceries',
  'family dollar': 'Groceries',
  'dollar tree': 'Groceries',
  'dollar general': 'Groceries',
  'buc‑ee’s': 'Groceries',
  'kwik trip': 'Groceries',
  'piggly wiggly': 'Groceries',

  // Transport merchants
  'uber': 'Transport',
  'lyft': 'Transport',
  'via': 'Transport',
  'shell': 'Transport',
  'exxon': 'Transport',
  'exxon mobil': 'Transport',
  'marathon': 'Transport',
  'chevron': 'Transport',
  'valero': 'Transport',
  'citgo': 'Transport',
  'phillips 66': 'Transport',
  'conoco': 'Transport',
  'bp': 'Transport',
  'sunoco': 'Transport',
  "love's": 'Transport',
  'pilot': 'Transport',
  'flying j': 'Transport',
  'speedway': 'Transport',
  'racetrac': 'Transport',
  "casey's": 'Transport',
  'maverik': 'Transport',
  'quiktrip': 'Transport',
  'kum & go': 'Transport',
  'thorntons': 'Transport',
  'buc‑ee’s': 'Transport',
  'amtrak': 'Transport',
  'greyhound': 'Transport',
  'megabus': 'Transport',
  'septa': 'Transport',
  'mta': 'Transport',
  'bart': 'Transport',
  'caltrain': 'Transport',
  'metrolink': 'Transport',
  'metro north': 'Transport',
  'sound transit': 'Transport',

  // Accommodation merchants
  'hilton': 'Accommodation',
  'marriott': 'Accommodation',
  'hyatt': 'Accommodation',
  'choice hotels': 'Accommodation',
  'wyndham': 'Accommodation',
  'ihg': 'Accommodation',
  'best western': 'Accommodation',
  'sonesta': 'Accommodation',
  'red roof inn': 'Accommodation',
  'four seasons': 'Accommodation',
  'holiday inn': 'Accommodation',
  'comfort inn': 'Accommodation',
  'days inn': 'Accommodation',
  'super 8': 'Accommodation',
  'la quinta': 'Accommodation',
  'crowne plaza': 'Accommodation',
  'residence inn': 'Accommodation',
  'airbnb': 'Accommodation',
  'vrbo': 'Accommodation',
  'booking.com': 'Accommodation',
  'expedia': 'Accommodation',
  'hotels.com': 'Accommodation',
  'priceline': 'Accommodation',
  'orbitz': 'Accommodation',

  // Entertainment merchants
  'netflix': 'Entertainment',
  'amazon prime video': 'Entertainment',
  'prime video': 'Entertainment',
  'disney plus': 'Entertainment',
  'disney+': 'Entertainment',
  'hulu': 'Entertainment',
  'max': 'Entertainment',
  'hbo max': 'Entertainment',
  'apple tv': 'Entertainment',
  'apple tv+': 'Entertainment',
  'paramount plus': 'Entertainment',
  'peacock': 'Entertainment',
  'starz': 'Entertainment',
  'showtime': 'Entertainment',
  'youtube premium': 'Entertainment',
  'spotify': 'Entertainment',
  'pandora': 'Entertainment',
  'apple music': 'Entertainment',
  'tidal': 'Entertainment',
  'siriusxm': 'Entertainment',
  'amc': 'Entertainment',
  'amc theatres': 'Entertainment',
  'regal': 'Entertainment',
  'cinemark': 'Entertainment',
  'fandango': 'Entertainment',
  'ticketmaster': 'Entertainment',
  'live nation': 'Entertainment',
  'stubhub': 'Entertainment',
  'axs': 'Entertainment',
  'eventbrite': 'Entertainment',
  'xbox game pass': 'Entertainment',
  'playstation plus': 'Entertainment',
  'nintendo switch online': 'Entertainment',
  'steam': 'Entertainment',
  'epic games': 'Entertainment',
  'espn+': 'Entertainment',
  'nba league pass': 'Entertainment',
  'mlb tv': 'Entertainment',
  'nfl+': 'Entertainment',

  // Utilities merchants
  'xfinity': 'Utilities',
  'comcast': 'Utilities',
  'at&t': 'Utilities',
  'att': 'Utilities',
  'verizon': 'Utilities',
  'verizon fios': 'Utilities',
  't‑mobile': 'Utilities',
  'tmobile': 'Utilities',
  'spectrum': 'Utilities',
  'charter': 'Utilities',
  'cox': 'Utilities',
  'centurylink': 'Utilities',
  'frontier': 'Utilities',
  'windstream': 'Utilities',
  'google fiber': 'Utilities',
  'starlink': 'Utilities',
  'hughesnet': 'Utilities',
  'dish': 'Utilities',
  'directv': 'Utilities',
  'pge': 'Utilities',
  'pg&e': 'Utilities',
  'con edison': 'Utilities',
  'duke energy': 'Utilities',
  'dominion energy': 'Utilities',
  'southern california edison': 'Utilities',
  'florida power & light': 'Utilities',
  'georgia power': 'Utilities',
  'national grid': 'Utilities',
  'xcel energy': 'Utilities',
  'sdg&e': 'Utilities',
  'nyseg': 'Utilities',

  // Healthcare merchants
  'cvs': 'Healthcare',
  'cvs pharmacy': 'Healthcare',
  'walgreens': 'Healthcare',
  'health mart': 'Healthcare',
  'good neighbor pharmacy': 'Healthcare',
  'gnc': 'Healthcare',
  'geno healthcare': 'Healthcare',
  'safeway pharmacy': 'Healthcare',
  'the vitamin shoppe': 'Healthcare',
  'albertsons pharmacy': 'Healthcare',
  'medicine shoppe': 'Healthcare',
  'rite aid': 'Healthcare',
  'publix pharmacy': 'Healthcare',
  'kroger pharmacy': 'Healthcare',
  'costco pharmacy': 'Healthcare',
  'meijer pharmacy': 'Healthcare',
  'kaiser permanente': 'Healthcare',
  'mayo clinic': 'Healthcare',
  'cleveland clinic': 'Healthcare',
  'hca healthcare': 'Healthcare',
  'ascension': 'Healthcare',
  'tenet healthcare': 'Healthcare',
  'sutter health': 'Healthcare',
  'blue cross': 'Healthcare',
  'blue shield': 'Healthcare',
  'bcbs': 'Healthcare',
  'unitedhealth': 'Healthcare',
  'aetna': 'Healthcare',
  'humana': 'Healthcare',
  'cigna': 'Healthcare',

  // Shopping merchants
  'amazon': 'Shopping',
  'amazon.com': 'Shopping',
  'target': 'Shopping',
  'best buy': 'Shopping',
  'home depot': 'Shopping',
  'lowe’s': 'Shopping',
  'lowes': 'Shopping',
  'bed bath & beyond': 'Shopping',
  'homegoods': 'Shopping',
  'tj maxx': 'Shopping',
  'marshalls': 'Shopping',
  'ross': 'Shopping',
  "macy's": 'Shopping',
  'nordstrom': 'Shopping',
  'kohls': 'Shopping',
  'jcpenney': 'Shopping',
  "dillard's": 'Shopping',
  'belk': 'Shopping',
  'academy sports': 'Shopping',
  "dick's sporting goods": 'Shopping',
  'ikea': 'Shopping',
  'five below': 'Shopping',
  'big lots': 'Shopping',
  'dollar tree': 'Shopping',
  'family dollar': 'Shopping',
  'dollar general': 'Shopping',
  'sams club': 'Shopping',
  "sam's club": 'Shopping',
  "bj's wholesale": 'Shopping',
  'gamestop': 'Shopping',
  'staples': 'Shopping',
  'office depot': 'Shopping',
  'office max': 'Shopping',
  'micro center': 'Shopping',
  'b&h photo': 'Shopping',
  'cabela’s': 'Shopping',
  'bass pro': 'Shopping',

  // Travel merchants
  'american airlines': 'Travel',
  'delta': 'Travel',
  'delta airlines': 'Travel',
  'southwest': 'Travel',
  'southwest airlines': 'Travel',
  'united': 'Travel',
  'united airlines': 'Travel',
  'alaska airlines': 'Travel',
  'jetblue': 'Travel',
  'spirit': 'Travel',
  'frontier': 'Travel',
  'allegiant': 'Travel',
  'hawaiian airlines': 'Travel',
  'sun country': 'Travel',
  'carnival cruise': 'Travel',
  'royal caribbean': 'Travel',
  'norwegian cruise': 'Travel',
  'msc cruises': 'Travel',
  'princess cruise': 'Travel',
  'disney cruise line': 'Travel',
  'expedia': 'Travel',
  'priceline': 'Travel',
  'kayak': 'Travel',
  'orbitz': 'Travel',
  'hotwire': 'Travel',
  'travelocity': 'Travel',
  'hopper': 'Travel',
  'trivago': 'Travel',
  'enterprise': 'Travel',
  'hertz': 'Travel',
  'avis': 'Travel',
  'budget': 'Travel',
  'alamo': 'Travel',
  'national': 'Travel',
  'thrifty': 'Travel',
  'dollar': 'Travel',
  'sixt': 'Travel',
  'u‑haul': 'Travel',
  'uhaul': 'Travel',
  'zipcar': 'Travel',
  'turo': 'Travel',

  // Education merchants
  'coursera': 'Education',
  'udemy': 'Education',
  'linkedin learning': 'Education',
  'edx': 'Education',
  'skillshare': 'Education',
  'masterclass': 'Education',
  'khan academy': 'Education',
  'pluralsight': 'Education',
  'udacity': 'Education',
  'futurelearn': 'Education',
  'codecademy': 'Education',
  'brilliant': 'Education',
  'datacamp': 'Education',
  'duolingo': 'Education',
  'rosetta stone': 'Education',
  'chegg': 'Education',
  'barnes & noble': 'Education',
  'bn': 'Education',
  'kaplan': 'Education',
  'princeton review': 'Education',

  // Fitness & Sports merchants
  'planet fitness': 'Fitness & Sports',
  'anytime fitness': 'Fitness & Sports',
  'orangetheory': 'Fitness & Sports',
  'f45 training': 'Fitness & Sports',
  'la fitness': 'Fitness & Sports',
  'crunch fitness': 'Fitness & Sports',
  '24 hour fitness': 'Fitness & Sports',
  'snap fitness': 'Fitness & Sports',
  'peloton': 'Fitness & Sports',
  'equinox': 'Fitness & Sports',
  "gold's gym": 'Fitness & Sports',
  'life time': 'Fitness & Sports',
  'club pilates': 'Fitness & Sports',
  "barry's bootcamp": 'Fitness & Sports',
  'soulcycle': 'Fitness & Sports',
  'retro fitness': 'Fitness & Sports',
  'workout anytime': 'Fitness & Sports',
  '9round': 'Fitness & Sports',
  'pure barre': 'Fitness & Sports',
  'cyclebar': 'Fitness & Sports',
  'row house': 'Fitness & Sports',
  'gympass': 'Fitness & Sports',
  'classpass': 'Fitness & Sports',
  'nike': 'Fitness & Sports',
  'adidas': 'Fitness & Sports',
  'lululemon': 'Fitness & Sports',
  'under armour': 'Fitness & Sports',
  'foot locker': 'Fitness & Sports',
  'champs sports': 'Fitness & Sports',
  'finish line': 'Fitness & Sports',
  'rogue fitness': 'Fitness & Sports',
  'big 5 sporting goods': 'Fitness & Sports',
  'academy sports': 'Fitness & Sports',

  // Personal Care merchants
  'supercuts': 'Personal Care',
  'smartstyle': 'Personal Care',
  'jcpenney salon': 'Personal Care',
  'cost cutters': 'Personal Care',
  'salon lofts': 'Personal Care',
  'amazing lash studio': 'Personal Care',
  'signature style salons': 'Personal Care',
  'holiday hair': 'Personal Care',
  'deka lash': 'Personal Care',
  'hairmasters': 'Personal Care',
  'great clips': 'Personal Care',
  'sport clips': 'Personal Care',
  'ulta': 'Personal Care',
  'ulta beauty': 'Personal Care',
  'sephora': 'Personal Care',
  'mac cosmetics': 'Personal Care',
  'clinique': 'Personal Care',
  'estee lauder': 'Personal Care',
  'bath & body works': 'Personal Care',
  'body shop': 'Personal Care',
  'lush': 'Personal Care',
  'aveda': 'Personal Care',
  'sally beauty': 'Personal Care',
  'beauty supply': 'Personal Care',
  'cosmo prof': 'Personal Care',
  'drybar': 'Personal Care',
  'european wax center': 'Personal Care',
  'massage envy': 'Personal Care',
  'hand and stone': 'Personal Care',
  'pro nails': 'Personal Care',
  'nail salon': 'Personal Care',
  'nail bar': 'Personal Care',
  'tanning salon': 'Personal Care',

  // Fees & Charges merchants
  'chase': 'Fees & Charges',
  'jp morgan chase': 'Fees & Charges',
  'bank of america': 'Fees & Charges',
  'wells fargo': 'Fees & Charges',
  'citibank': 'Fees & Charges',
  'citi': 'Fees & Charges',
  'us bank': 'Fees & Charges',
  'pnc bank': 'Fees & Charges',
  'pnc': 'Fees & Charges',
  'truist': 'Fees & Charges',
  'capital one': 'Fees & Charges',
  'td bank': 'Fees & Charges',
  'bmo': 'Fees & Charges',
  'first citizens bank': 'Fees & Charges',
  'citizens bank': 'Fees & Charges',
  'fifth third bank': 'Fees & Charges',
  'm&t bank': 'Fees & Charges',
  'huntington bank': 'Fees & Charges',
  'ally bank': 'Fees & Charges',
  'keybank': 'Fees & Charges',
  'hsbc': 'Fees & Charges',
  'regions bank': 'Fees & Charges',
  'american express': 'Fees & Charges',
  'amex': 'Fees & Charges',
  'discover': 'Fees & Charges',
  'visa': 'Fees & Charges',
  'mastercard': 'Fees & Charges',
  'paypal': 'Fees & Charges',
  'venmo': 'Fees & Charges',
  'cash app': 'Fees & Charges',
  'zelle': 'Fees & Charges',
  'stripe': 'Fees & Charges',
  'square': 'Fees & Charges',
  'intuit': 'Fees & Charges',
  'quickbooks': 'Fees & Charges',
  'coinbase': 'Fees & Charges',
  'robinhood': 'Fees & Charges',
  'irs': 'Fees & Charges',
  'dmv': 'Fees & Charges',
  'state tax': 'Fees & Charges',
  'property tax': 'Fees & Charges',
  'court fee': 'Fees & Charges',
  'hoa': 'Fees & Charges',
  'hoa fee': 'Fees & Charges',
  'license fee': 'Fees & Charges',
  'passport fee': 'Fees & Charges',
  'visa fee': 'Fees & Charges',

  // Other merchants
  'goodwill': 'Other',
  'salvation army': 'Other',
  'red cross': 'Other',
  'united way': 'Other',
  'gofundme': 'Other',
  'go fund me': 'Other',
  'patreon': 'Other',
  'kickstarter': 'Other',
  'indiegogo': 'Other',
  'petco': 'Other',
  'petsmart': 'Other',
  'church': 'Other',
  'vet': 'Other',
  'vet bill': 'Other',
  'home improvement': 'Other',
  'contractor': 'Other',
  'daycare': 'Other',
  'babysitter': 'Other',
  'insurance': 'Other',
  'irs payment': 'Other',
  'dmv fee': 'Other'
};